services:
  ui:
    image: vilheim/chirpr:ui-latest
    build:
      context: ./ui/
      args:
        - VITE_HOST_URL=${VITE_HOST_URL}
    environment:
        - VITE_HOST_URL=${VITE_HOST_URL}
        - VITE_BLOB_URL=${VITE_BLOB_URL}
        - NODE_ENV=development
    env_file:
      - .env
    ports:
      - 5173:5173
  server:
    image: vilheim/chirpr:api-latest
    build:
      context: ./api/
      target: development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5042
      - AppSettings__Frontend=https://www.chirpr.au
      - AppSettings__Domain=chirpr.au
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=chirpr-local;Username=postgres;Password=example
      - ConnectionStrings__BlobURL=https://media.chirpr.au
      - Jwt__Key="test1232131231231231231223131331"
      - Jwt__Issuer=https://api.chirpr.au
      - Jwt__Audience=https://www.chirpr.au
      - Jwt__TokenLifetimeMinutes=15
      - Logging__LogLevel__Default=Debug
      - ConnectionStrings__BlobStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://10.0.1.8
    ports:
      - 5042:5042
  postgres:
    image: postgres:14
    restart: always
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=chirpr-local
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  azure-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - default-azurite-volume:/data mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 -l /data"
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ui
      - server
    restart: unless-stopped
volumes:
  db:
  default-azurite-volume:
  caddy_data:
  caddy_config: