# Use the .NET SDK image for development
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS development

# Set the working directory
WORKDIR /app

# Copy only the project file (optimizing layer caching)
COPY *.csproj ./

# Restore dependencies
RUN dotnet restore

# Copy the rest of the application
COPY . .

# Expose ports
EXPOSE 5042

# Enable Hot Reload with dotnet watch
CMD ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:5042"]
